services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: brain-tumor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Models:/app/Models
    restart: always

  frontend:
    build:
      context: ./UI/BrainTumorDetectionUI
      dockerfile: Dockerfile.frontend
    container_name: brain-tumor-frontend
    ports:
      - "3000:3000"
  
    volumes:
      - ./UI/BrainTumorDetectionUI:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always